### ISSUE TITLE
[TASK] Create basic GitHub Actions CI workflow

### ISSUE THREAD

**Issue by ncolesummers** [ncolesummers/idaho-data#16]
## Task Type
Implementation (Green Phase)

## Parent Issue
#4

## Description
Set up the foundational GitHub Actions workflow for continuous integration. This will run on every push and pull request to ensure code quality.

## Checklist
- [ ] Create `.github/workflows/` directory structure
- [ ] Create `ci.yml` file with basic workflow
- [ ] Configure workflow triggers:
  - [ ] On push to main and develop branches
  - [ ] On pull requests to main
  - [ ] Manual trigger with workflow_dispatch
- [ ] Set up Go environment:
  - [ ] Use actions/checkout@v4
  - [ ] Use actions/setup-go@v5 with Go 1.21
  - [ ] Cache Go modules with actions/cache
- [ ] Add basic build job:
  - [ ] Download dependencies
  - [ ] Build the project
  - [ ] Run go vet
  - [ ] Run gofmt check
- [ ] Add basic test job:
  - [ ] Run unit tests
  - [ ] Generate test report
  - [ ] Upload test results as artifact
- [ ] Test workflow:
  - [ ] Create a test branch
  - [ ] Make small change
  - [ ] Open PR and verify workflow runs
  - [ ] Check all steps pass

## Priority
P0 - Critical

## Time Estimate
1 hour

## Technical Details
Basic workflow structure:
```yaml
name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  GO_VERSION: '1.21'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
```

## Definition of Done
- [ ] Workflow file created and committed
- [ ] Workflow runs on push and PR
- [ ] All checks pass
- [ ] Build artifacts generated
- [ ] Team notified of new CI process
- [ ] Documentation updated
