### ISSUE TITLE
[TASK] Add test and coverage jobs to CI workflow

### ISSUE THREAD

**Issue by ncolesummers** [ncolesummers/idaho-data#17]
## Task Type
Implementation (Green Phase)

## Parent Issue
#4

## Description
Enhance the CI workflow by adding dedicated test and coverage reporting jobs. Integrate with Codecov for coverage visualization.

## Checklist
- [ ] Update `ci.yml` to add test job:
  - [ ] Configure test job to depend on build
  - [ ] Run tests with race detector
  - [ ] Generate coverage profile
  - [ ] Create test summary report
- [ ] Add coverage reporting:
  - [ ] Sign up for Codecov.io
  - [ ] Add repository to Codecov
  - [ ] Generate coverage.txt file
  - [ ] Upload to Codecov using codecov-action
- [ ] Configure test output:
  - [ ] Use gotestsum for better test output
  - [ ] Generate JUnit XML report
  - [ ] Upload test results as artifacts
- [ ] Add coverage badge:
  - [ ] Get badge URL from Codecov
  - [ ] Add to README.md
  - [ ] Verify badge displays correctly
- [ ] Set coverage thresholds:
  - [ ] Create codecov.yml configuration
  - [ ] Set minimum coverage to 80%
  - [ ] Configure PR comments
- [ ] Test the enhanced workflow:
  - [ ] Create PR with new tests
  - [ ] Verify coverage report appears
  - [ ] Check Codecov integration

## Priority
P0 - Critical

## Time Estimate
1 hour

## Technical Details
Test job configuration:
```yaml
test:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        
    - name: Run tests
      run: |
        go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.txt
        flags: unittests
        name: codecov-umbrella
```

## Definition of Done
- [ ] Test job added to workflow
- [ ] Coverage reports generated
- [ ] Codecov integration working
- [ ] Badge added to README
- [ ] PR comments show coverage
- [ ] Documentation updated
