### ISSUE TITLE
[TASK] Configure golangci-lint in CI pipeline

### ISSUE THREAD

**Issue by ncolesummers** [ncolesummers/idaho-data#18]
## Task Type
Configuration

## Parent Issue
#4

## Description
Add comprehensive Go linting to the CI pipeline using golangci-lint to catch code quality issues early.

## Checklist
- [ ] Create `.golangci.yml` configuration file:
  - [ ] Enable recommended linters
  - [ ] Configure linter settings
  - [ ] Set exclusion rules if needed
  - [ ] Add custom linting rules
- [ ] Add lint job to CI workflow:
  - [ ] Use golangci/golangci-lint-action
  - [ ] Configure version pinning
  - [ ] Set working directory
  - [ ] Enable annotations for PRs
- [ ] Configure linters to enable:
  - [ ] gofmt - code formatting
  - [ ] govet - suspicious constructs
  - [ ] ineffassign - ineffectual assignments
  - [ ] misspell - spelling mistakes
  - [ ] staticcheck - static analysis
  - [ ] gosec - security issues
  - [ ] errcheck - unchecked errors
- [ ] Test linting locally:
  - [ ] Install golangci-lint
  - [ ] Run `golangci-lint run`
  - [ ] Fix any issues found
- [ ] Add pre-commit hook:
  - [ ] Configure golangci-lint in pre-commit
  - [ ] Test hook works correctly
- [ ] Update Makefile:
  - [ ] Add `make lint` command
  - [ ] Add `make lint-fix` for auto-fixes

## Priority
P0 - Critical

## Time Estimate
45 minutes

## Technical Details
Example .golangci.yml:
```yaml
run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - misspell
    - gosec
    - gosimple
    - goconst
    - gocyclo
    - dupl

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
```

## Definition of Done
- [ ] golangci.yml created
- [ ] Lint job added to CI
- [ ] All code passes linting
- [ ] Pre-commit hook configured
- [ ] Make commands added
- [ ] Team trained on linting
