### ISSUE TITLE
[TASK] Set up pre-commit hooks for code quality

### ISSUE THREAD

**Issue by ncolesummers** [ncolesummers/idaho-data#19]
## Task Type
Configuration

## Parent Issue
#5

## Description
Configure pre-commit hooks to automatically check code quality before commits, catching issues early in the development process.

## Checklist
- [ ] Install pre-commit framework:
  - [ ] Add installation to setup documentation
  - [ ] Test installation with `pre-commit --version`
- [ ] Create `.pre-commit-config.yaml`:
  - [ ] Add pre-commit-hooks repo for basics
  - [ ] Add golang specific hooks
  - [ ] Configure hook settings
- [ ] Configure basic hooks:
  - [ ] trailing-whitespace removal
  - [ ] end-of-file-fixer
  - [ ] check-yaml validity
  - [ ] check-added-large-files
  - [ ] check-merge-conflict markers
- [ ] Add Go-specific hooks:
  - [ ] go-fmt - format Go code
  - [ ] go-imports - organize imports
  - [ ] go-vet - check for issues
  - [ ] go-mod-tidy - keep go.mod clean
  - [ ] golangci-lint - comprehensive linting
- [ ] Install hooks locally:
  - [ ] Run `pre-commit install`
  - [ ] Verify `.git/hooks/pre-commit` exists
- [ ] Test the hooks:
  - [ ] Create file with formatting issues
  - [ ] Attempt to commit
  - [ ] Verify hooks run and fix issues
- [ ] Add to developer setup:
  - [ ] Update setup script
  - [ ] Document in README
  - [ ] Add to Makefile

## Priority
P0 - Critical

## Time Estimate
45 minutes

## Technical Details
Example .pre-commit-config.yaml:
```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-vet
      - id: go-mod-tidy

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.55.2
    hooks:
      - id: golangci-lint
```

## Definition of Done
- [ ] pre-commit config created
- [ ] All hooks installed and working
- [ ] Tested with actual commits
- [ ] Setup documentation updated
- [ ] Team trained on usage
- [ ] Make command available
